%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[10.2.0.0/24]"
    EXTERNAL_NET: "!$HOME_NET"

default-rule-path: /etc/suricata/rules
rule-files:
 - suricata.rules

af-packet:
  - interface: eth0
    cluster-id: 98
    cluster-type: cluster_flow
    defrag: yes